version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile-tools
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
        - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
