version: 2
jobs:
  build:
    docker:
      - image: swift:4.0
    steps:
      - run:
          name: Install system level packages
          command: apt-get update && apt-get install -y libmysqlclient-dev
      - checkout
      - run:
          name: Install dependencies
          command: swift package resolve
      - run:
          name: Build
          command: swift build -c release
      - run:
          name: Test
          command: swift test
